[package]
name = "pi_ordmap"
version = "0.3.0"
authors = ["suncy <530739162@qq.com>"]
edition = "2021"
description = "Ord Map"
repository = "https://github.com/GaiaWorld/pi_ordmap.git"
license = "MIT OR Apache-2.0"
keywords = ["pi", "ordmap"]